name: 'Setup gcloud environment'
description: 'Setup a gcloud environment and add it to the PATH'
author: 'GoogleCloudPlatform'
inputs:
  version:
    description: 'The version of the gcloud SDK to be installed.  Example: 278.0.0'
    default: 'latest'
    required: false
  service_account_email:
    description: 'The service account email which will be used for authentication.'
    required: false
  service_account_key:
    description: 'The service account key which will be used for authentication.'
    required: true
  export_default_credentials:
    description: |-
      Export the provided credentials as Google Default Application Credentials.
      This will make the credentials available to later steps via the
      GOOGLE_APPLICATION_CREDENTIALS environment variable. Future steps that
      consume Default Application Credentials will automatically detect and use
      these credentials.
    default: false
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
